tasks:
  - init: |
      cp .env.dist .env
      docker compose build
      docker compose run --rm app composer install
  - command: |
      docker compose up

ports:
  - port: 8080
    onOpen: open-browser