#!/bin/sh
set -e

MAIN_PROCESS_NAME=$(ps -ao comm= | head -n 1)

if [ "$MAIN_PROCESS_NAME" != 'php-fpm' ]; then
  exit 0
fi

export SCRIPT_NAME=/ping
export SCRIPT_FILENAME=/ping
export REQUEST_METHOD=GET

if cgi-fcgi -bind -connect 127.0.0.1:9000; then
  exit 0
fi

exit 1
